import{S as w,i as u,a as E}from"./assets/vendor-BBSqv8W6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const r of n.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&o(r)}).observe(document,{childList:!0,subtree:!0});function a(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(e){if(e.ep)return;e.ep=!0;const n=a(e);fetch(e.href,n)}})();const S=document.querySelector(".app-form");document.querySelector("#appGallery");const p=document.querySelector("#galleryList");let x,i=1,c;console.log(`
  Search Photos API: https://pixabay.com/api/docs/

  Search Active Page: ${i}
  Search Max Page: ${c}
  `);const b=s=>{const t=document.createElement("li");t.classList.add("gallery-item"),t.dataset.source=s.largeImageURL;const a=document.createElement("a");a.href=s.largeImageURL,a.classList.add("gallery-link"),a.style.color="black";const o=document.createElement("img");o.src=s.webformatURL,o.alt=s.tags,o.width=360,o.height=200;const e=document.createElement("div");e.classList.add("content");const n=document.createElement("div");n.classList.add("info");const r=document.createElement("h5");r.classList.add("key"),r.textContent="Likes",n.appendChild(r);const h=document.createElement("p");h.classList.add("value"),h.textContent=s.likes,n.appendChild(h);const l=document.createElement("div");l.classList.add("info");const g=document.createElement("h5");g.classList.add("key"),g.textContent="Views",l.appendChild(g);const y=document.createElement("p");y.classList.add("value"),y.textContent=s.views,l.appendChild(y);const d=document.createElement("div");d.classList.add("info");const f=document.createElement("h5");f.classList.add("key"),f.textContent="Comments",d.appendChild(f);const L=document.createElement("p");L.classList.add("value"),L.textContent=s.views,d.appendChild(L);const m=document.createElement("div");m.classList.add("info");const C=document.createElement("h5");C.classList.add("key"),C.textContent="Downloads",m.appendChild(C);const v=document.createElement("p");v.classList.add("value"),v.textContent=s.downloads,m.appendChild(v),e.appendChild(n),e.appendChild(l),e.appendChild(d),e.appendChild(m),a.appendChild(o),t.appendChild(e),t.appendChild(a),p.appendChild(t)};let q=new w(".gallery li > a",{captionsData:"alt",captionDelay:350});const D=(s,t)=>new Promise(async(a,o)=>{if(console.log("SearchPhotos()",s,t),t>c)i=1,t=1;else{const e=await E.get("https://pixabay.com/api/",{params:{key:"49344582-c64095957e0f61b264d1bf806",q:s,images_type:"photo",orientation:"all",safesearch:"false",page:t,per_page:40}});c=parseFloat(e.data.totalHits/e.data.hits.lenght).toFixed(0),console.log(`
        Search Active Text: ${x}
        Search Active Page: ${i}
        Search Max Page: ${c}
      `),e.data.hits.lenght===0&&u.error({position:"topRight",color:"red",message:"Sorry, there are no images matching your search query.Please try again!!"}),i<c&&(document.querySelector("#nextPage").style.display="block",document.querySelector("#nextPage").textContent=`Next Page (${sear+1})`),a(e)}}),P=async()=>{const a=(await D(x,i)).data.hits;p.innerHTML="",a.lenght===0?u.error({position:"topRight",color:"red",message:"Sorry, there are no images matching your search query.Please try again!!"}):(a.forEach(o=>{b(o)}),q.refresh())};S.addEventListener("submit",async s=>{s.preventDefault(),p.innerHTML="";const t=s.target.elements.search.value;if(x=t,i=1,c=void 0,t==="")return u.warning({position:"topRight",color:"yellow",message:"Please enter a valid search query!!"}),!1;{const a=document.createElement("li");a.classList.add("gallery-item");const o=document.createElement("span");o.classList.add("loader"),a.appendChild(o),a.style.textAlign="center",a.style.border="none",p.appendChild(a),P(),s.target.reset()}});document.querySelector("#nextPage").addEventListener("click",async s=>{i++,P();const t=document.querySelector(".gallery-item");if(t){const a=t.getBoundingClientRect().height;window.scrollBy({top:a*2.75,behavior:"smooth"})}i===c&&(document.querySelector("#nextPage").dispatchEvent("click"),u.info({positon:"topRight",message:"we're sorry,but you've reached the end of the search results"}))});
//# sourceMappingURL=index.js.map
